// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using darsakApi.Data;

#nullable disable

namespace darsakApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611104845_MaterialNotMappedFields")]
    partial class MaterialNotMappedFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("darsakApi.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VideoThumbnail")
                        .HasColumnType("longtext");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("darsakApi.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StudentStageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentStageId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("darsakApi.Models.MaterialSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialSources");
                });

            modelBuilder.Entity("darsakApi.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("darsakApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FatherPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Government")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StudentStageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentStageId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("darsakApi.Models.StudentStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("StudentStages");
                });

            modelBuilder.Entity("darsakApi.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Government")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<int>("LessonCount")
                        .HasColumnType("int");

                    b.Property<int>("MaterialCount")
                        .HasColumnType("int");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("StageKind")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StudentSubCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("darsakApi.Models.TeacherCertification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherCertifications");
                });

            modelBuilder.Entity("darsakApi.Models.TeacherMaterial", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("TeacherMaterials");
                });

            modelBuilder.Entity("darsakApi.Models.Lesson", b =>
                {
                    b.HasOne("darsakApi.Models.Material", "Material")
                        .WithMany("Lessons")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("darsakApi.Models.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("darsakApi.Models.Material", b =>
                {
                    b.HasOne("darsakApi.Models.StudentStage", "StudentStage")
                        .WithMany()
                        .HasForeignKey("StudentStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentStage");
                });

            modelBuilder.Entity("darsakApi.Models.MaterialSource", b =>
                {
                    b.HasOne("darsakApi.Models.Material", "Material")
                        .WithMany("MaterialSources")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("darsakApi.Models.Post", b =>
                {
                    b.HasOne("darsakApi.Models.Material", "Material")
                        .WithMany("Posts")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("darsakApi.Models.Student", b =>
                {
                    b.HasOne("darsakApi.Models.StudentStage", "StudentStage")
                        .WithMany()
                        .HasForeignKey("StudentStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentStage");
                });

            modelBuilder.Entity("darsakApi.Models.TeacherCertification", b =>
                {
                    b.HasOne("darsakApi.Models.Teacher", "Teacher")
                        .WithMany("Certifications")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("darsakApi.Models.TeacherMaterial", b =>
                {
                    b.HasOne("darsakApi.Models.Material", "Material")
                        .WithMany("TeacherMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("darsakApi.Models.Teacher", "Teacher")
                        .WithMany("TeacherMaterials")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("darsakApi.Models.Material", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("MaterialSources");

                    b.Navigation("Posts");

                    b.Navigation("TeacherMaterials");
                });

            modelBuilder.Entity("darsakApi.Models.Teacher", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Lessons");

                    b.Navigation("TeacherMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
